//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reminder.Storage.DbStorage.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reminder.Storage.DbStorage.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- fill tables with test data
        ///
        ///DECLARE @id0 AS UNIQUEIDENTIFIER
        ///DECLARE @id1 AS UNIQUEIDENTIFIER
        ///DECLARE @id2 AS UNIQUEIDENTIFIER
        ///DECLARE @id3 AS UNIQUEIDENTIFIER
        ///DECLARE @id4 AS UNIQUEIDENTIFIER
        ///DECLARE @id5 AS UNIQUEIDENTIFIER
        ///DECLARE @id6 AS UNIQUEIDENTIFIER
        ///DECLARE @id7 AS UNIQUEIDENTIFIER
        ///DECLARE @id8 AS UNIQUEIDENTIFIER
        ///DECLARE @id9 AS UNIQUEIDENTIFIER
        ///
        ///EXECUTE dbo.CreateReminder &apos;2020-01-10 00:00&apos;,	&apos;testChat0&apos;,	&apos;testMessage0&apos;,		&apos;Awaiting&apos;,		@id0 OUTPUT
        ///EXECUTE dbo.CreateReminder &apos;2020-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- drop foreign keys
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[Reminder]&apos;) AND type in (N&apos;U&apos;))
        ///ALTER TABLE [dbo].[Reminder] DROP CONSTRAINT IF EXISTS [FK_Reminder_ChatId]
        ///GO
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ReminderStatus]&apos;) AND type in (N&apos;U&apos;))
        ///ALTER TABLE [dbo].[ReminderStatus] DROP CONSTRAINT IF EXISTS [FK_ReminderStatus_ReminderId]
        ///GO
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ReminderStatus] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE IF EXISTS dbo.GetRemindersCount
        ///GO
        ///CREATE PROCEDURE dbo.GetRemindersCount(
        ///	@count AS INT OUTPUT
        ///)
        ///AS BEGIN
        ///	SET NOCOUNT ON
        ///
        ///	SELECT @count = COUNT(*)
        ///	FROM dbo.Reminder
        ///END
        ///GO
        ///
        ///DROP PROCEDURE IF EXISTS dbo.GetChatId
        ///GO
        ///CREATE PROCEDURE dbo.GetChatId(
        ///	@chat AS VARCHAR(15),
        ///	@id AS INT OUTPUT
        ///)
        ///AS BEGIN
        ///	SET NOCOUNT ON
        ///	
        ///	DECLARE @tempId AS INT
        ///
        ///	SELECT @tempId = c.Id
        ///	FROM dbo.Chat c
        ///	WHERE c.Chat = @chat
        ///
        ///	IF(@tempId IS NULL)
        ///	BEGIN
        ///		INSERT INTO dbo.Chat (Chat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SPs {
            get {
                return ResourceManager.GetString("SPs", resourceCulture);
            }
        }
    }
}
